### ISSUE TITLE
I can't click login

### ISSUE THREAD

**Issue by aeongdesu** [TheOmyNomy/Klserjht#1]
![](https://bread.shx.gg/PKdhsD.png) 

idk unable to login

**Comment by TheOmyNomy** [comment]
I wasn't able to consistently reproduce, however I think I've fixed the issue with c4c5f35e40602dcf015aa1f147244ff162296d1e.
I've also released update [2021.01.22.0](https://github.com/TheOmyNomy/Klserjht/releases/tag/2021.01.22.0) with this commit included. Let me know if it still occurs!

**Comment by TheOmyNomy** [comment]
I wasn't able to consistently reproduce this issue, however I think I've fixed it with c4c5f35e40602dcf015aa1f147244ff162296d1e.
I've also released update [2021.01.22.0](https://github.com/TheOmyNomy/Klserjht/releases/tag/2021.01.22.0) with this commit included. Let me know if it still occurs!

**Comment by aeongdesu** [comment]
![image](https://user-images.githubusercontent.com/50764666/105502959-5bbaf500-5d09-11eb-9a2c-0446dac7f48a.png)
Now working, Thank you for fixing!!
