### ISSUE TITLE
!link! not working

### ISSUE THREAD

**Issue by Hunteriwi** [TheOmyNomy/Klserjht#2]
I tried to use it, but the !link! attribute is broken, always throws a broken link instead of the map link.
![image](https://user-images.githubusercontent.com/45808925/140658364-5e9e82c2-cd58-4c55-93f2-24ae751925e1.png)
It is my config that's broken or the program itself?
![image](https://user-images.githubusercontent.com/45808925/140658373-b3ce12c1-eeda-4ea4-896c-fa1a9b610ca6.png)

**Comment by TheOmyNomy** [comment]
A recent osu! update broke the memory reader library Klserjht uses to fetch the artist, title, etc.
I've released an update [2021.11.09.0](https://github.com/TheOmyNomy/Klserjht/releases/tag/2021.11.09.0) that should solve your issue. Let me know if it still occurs!

**Comment by Hunteriwi** [comment]
Hello, it's me again, the program it's not working again, probably same issue as before.

**Comment by Hunteriwi** [comment]
> A recent osu! update broke the memory reader library Klserjht uses to fetch the artist, title, etc. I've released an update [2021.11.09.0](https://github.com/TheOmyNomy/Klserjht/releases/tag/2021.11.09.0) that should solve your issue. Let me know if it still occurs!

Hello, it's me again, the program it's not working again, probably same issue as before.
