### ISSUE TITLE
Broke again, probably the same issue as before

### ISSUE THREAD

**Issue by Hunteriwi** [TheOmyNomy/Klserjht#3]
Hi, it's me again, it broke again, shows a broken link with a 0 ID map.

---

A recent osu! update broke the memory reader library Klserjht uses to fetch the artist, title, etc.
I've released an update [2021.11.09.0](https://github.com/TheOmyNomy/Klserjht/releases/tag/2021.11.09.0) that should solve your issue. Let me know if it still occurs!

_Originally posted by @TheOmyNomy in https://github.com/TheOmyNomy/Klserjht/issues/2#issuecomment-963502234_

**Comment by TheOmyNomy** [comment]
A recent osu! update broke the memory reader library... again.
I've released an update [2022.06.06.0](https://github.com/TheOmyNomy/Klserjht/releases/tag/2022.06.06.0) that should solve your issue. Let me know if it still occurs!
