### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by Hunteriwi** [TheOmyNomy/Klserjht#6]
The bots writes the links as the following:

 _https://osu.ppy.sh/beatmaps/#######_

 instead of:
 
 _https://osu.ppy.sh/beatmapsets/######_

Peppy changed the hyperlinks of maps.

**Comment by miyuki-ts** [comment]
I have a similar issue, where !version! doesn't work, it output in this format:

 Now Playing: !artist! - !title! (!creator!) [!version!], BeatMap ID: !id!
 Now Playing: xi - FREEDOM DiVE (Aistre) [], BeatMap ID: 1667560

**Comment by TheOmyNomy** [comment]
Thanks for reporting the issue!

This has been fixed in the latest release. You can update to it by launching osu!np and clicking the update button when it pops up. You can also view the release / changelog here: [2023.12.22.0](https://github.com/TheOmyNomy/OsuNowPlaying/releases/tag/2023.12.22.0)
