### ISSUE TITLE
!np command only works for streamer account 

### ISSUE THREAD

**Issue by miyuki-ts** [TheOmyNomy/Klserjht#7]
![image](https://github.com/TheOmyNomy/OsuNowPlaying/assets/93956624/83c252c5-7fd2-4f2a-8d98-01d037bfff9e)
this is on different account chuuflow

and it works if i use my streamer / main account
![image](https://github.com/TheOmyNomy/OsuNowPlaying/assets/93956624/7cf2a65d-9623-40f0-9aa6-8eb86e994988)

**Comment by TheOmyNomy** [comment]
Please send a screenshot of osu!np with the advanced section visible so I can see your settings.

**Comment by miyuki-ts** [comment]
It's my issue. I ask my friend. he test it for me and it works perfect, I am sorry for the issue.
